### ISSUE TITLE
The big todo list!

### ISSUE THREAD

**Issue by Terrails** [Terrails/NetherLiving#1]
## TODO list

World Generation:
- [ ] Biome with trees and a little bit of life like overworld
- [ ] Biome with some kind of a dungeon
- [ ] Some kind of crystal biome or deposits?
- [ ] A dungeon with couple of floors and a boss at the top... probably some kind of rare prize
- [ ] Generate nether equivalent of ores and some extra ores like copper, tin, zinc...
- [ ] Villages hanging from the nether ceiling... soon™
***
Magical Armor:
- [ ] Probably find a better name
- [ ] Add a bunch of abilities
- [ ] Make an API for other mods
***
Entities:
- [ ] A projectile which pulls any entity it hits
- [ ] A mob swimming in lava... similar to squid but aggressive and make it throw those projectiles
- [ ] More types of pigman
